train_list: '/Data/luy8/glomeruli/renal/json/trainset1.json'

val_list: '/Data/luy8/glomeruli/renal/json/fold4.json'

test_list: '/Data/luy8/glomeruli/renal/json/fold5.json'

output_csv_dir: '/Data/luy8/glomeruli/exp_results/config_renal'

dataset: 'renal'

pretrain: True

num_classes: 5

epochs: 40

start_epoch: 0

batch_size: 16

lr: 1.0e-5

network: 102

num_workers: 16

beta: 1

cutmix_prob: 0

circlemix_prob: 0

cutout_prob: 0